name: daddylive-channels
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allows manual trigger from the Actions tab

env:
  m_filename: daddylive-channels.m3u8
  t_filename: daddylive-channels-tivimate.m3u8

jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Manila

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download M3U8 files
        run: |
          BASE_URL="${{ secrets.DADDYLIVE_CHANNELS_URL }}"
          CLEAN_URL="${BASE_URL%/}"
          
          echo "Downloading M3U8 files"
          curl --retry 3 --retry-delay 5 -fSL "$CLEAN_URL" -o "${{ env.m_filename }}" || { echo "Download failed"; exit 1; }

          echo "Downloading Tivimate M3U8 files"
          curl --retry 3 --retry-delay 5 -fSL "$CLEAN_URL/tivimate" -o "${{ env.t_filename }}" || { echo "Download failed"; exit 1; }

      - name: Log the downloaded M3U8 file details
        run: |
          for file in "${{ env.m_filename }}" "${{ env.t_filename }}"; do
            if [ -f "$file" ]; then
              echo "$file downloaded successfully."
              ls -lh "$file"
            else
              echo "Failed to download $file."
            fi
          done

      - name: Commit and push the M3U8 files (Squash Commit)
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"

          git add "${{ env.m_filename }}" "${{ env.t_filename }}"

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update M3U8 files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
